### ISSUE TITLE
Tag v1 hasn't been updated since 2021

### ISSUE THREAD

**Issue by jannaspam** [1Password/load-secrets-action#23]
Looks like `v1` tag is still pointing to the really old code (2021) which is really confusing as in your documentation you are using it.

```
      - name: Load secret
        id: op-load-secret
        uses: 1password/load-secrets-action@v1
```

Would be great if you could tag the latest version (`v1.1.1` or even `v1.1.2` with a fix from [#20](https://github.com/1Password/load-secrets-action/issues/20)). My assumption is that `v1` will include all the non-breaking changes.

**Comment by edif2008** [comment]
Hey @jannaspam,

Thank you so much for spotting this. Indeed, the `v1` tag was no longer pointing to the latest version of the action (which is currently `v1.1.2`). I've just updated the tag to point to it. 

Let me know if this addresses your issue and I will make sure that this `v1` tag update will become a part of our release process for the upcoming versions. 😄

**Comment by jannaspam** [comment]
Looks great, thank you for really prompt response :)
