### ISSUE TITLE
Permission denied when using self-hosted

### ISSUE THREAD

**Issue by anggutie-dev** [1Password/load-secrets-action#26]
When using the self-hosted version, specifically using kubernetes and the summerwind image (summerwind/actions-runner-dind:ubuntu-20.04) I got the following:

```
Authenticated with CONNECT 
Archive:  op.zip
error:  cannot create /usr/local/bin/op.sig
        Permission denied
error:  cannot create /usr/local/bin/op
        Permission denied
Error: The process '/usr/bin/sh' failed with exit code 50
```
Since it tries to decompress the file in that directory and that directory is owned by root, it throws an error. The pod runs with user "runner"

Any thoughts?

**Comment by utamas** [comment]
while this issue get's solved, I guess I'll have to follow on the footsteps of giants and use a customized runner image with `sudo chmod -R 777 /usr/local/bin` applied in the image :(
