### ISSUE TITLE
Latest build is broken

### ISSUE THREAD

**Issue by zheli** [1Password/load-secrets-action#50]
The base image is missing `jq` package.
![image](https://github.com/1Password/load-secrets-action/assets/157039/ae918c42-b0ed-47ad-8b3b-8ac6efc65b4d)

**Comment by edif2008** [comment]
Hey there.
This is quite interesting. Our testing pipelines use `ubuntu-latest` and `macos-latest` which are base images from GitHub and those seem to have `jq` in them. 🤔 

It's still a safer thing to assume that `jq` is not available everywhere, therefore I've made this quickfix PR: https://github.com/1Password/load-secrets-action/pull/51

**Comment by edif2008** [comment]
Fixed as part of release [v1.3.1](https://github.com/1Password/load-secrets-action/releases/tag/v1.3.1)
