### ISSUE TITLE
Getting node depecarted warning while using 1password/load-secrets-action

### ISSUE THREAD

**Issue by thisalihassan** [1Password/load-secrets-action#70]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: 1password/load-secrets-action@v1.

**Comment by pmalek** [comment]
https://github.com/1Password/load-secrets-action/releases/tag/v2.0.0 already includes the update to Node 20.

**Comment by getalihassan** [comment]
oh thanks I wasn't aware a 2.0 has been release. I will be closing this issue then

**Comment by thisalihassan** [comment]
oh thanks I wasn't aware a 2.0 has been release. this issue can be closed
