### ISSUE TITLE
Docs still show using v1

### ISSUE THREAD

**Issue by rfay** [1Password/load-secrets-action#78]
The docs on https://developer.1password.com/docs/ci-cd/github-actions/

still show using v1. I imagine you want people to use v2

> uses: 1password/load-secrets-action/configure@v1

**Comment by edif2008** [comment]
Thank you @rfay for raising this! This is quite a nice catch.

I've raised this with the team and we will update the documentation soon.

**Comment by edif2008** [comment]
Hey @rfay!
We've updated the documentation to mention v2. Thank you for your feedback! 😄
