### ISSUE TITLE
Security considerations for public GitHub Actions

### ISSUE THREAD

**Issue by hazcod** [1Password/load-secrets-action#8]
Hi,

I'm curious if there are some security considerations for the 1Password Connect server since it should be exposed publicly.

**Comment by verkaufer** [comment]
Hi @hazcod -

Yes, there are some security considerations if you choose to expose your Connect server publicly:
1. **Use TLS**: We have **[a guide](https://github.com/1Password/connect#tls)** for configuring the deployment to use LetsEncrypt certificates or a certificate you supply manually

2. Review some basic information about **[1Password Connect security](https://support.1password.com/connect-security/)**

3. You may want to put the Connect server behind a load balancer if you expect heavy load on the server. The public-facing API server can scale horizontally (i.e. many instances can run at once). 

If you have any specific questions, I can try to get those answers for you.

**Comment by hazcod** [comment]
Hi @verkaufer ! I have no issue discussing here FWIW.
Needing 1P secrets in GitHub Actions would mean exposing the Connect server to anyone (or at least the whole of GitHub).
We do not have any plans for running our own hosted GitHub Actions at this point.

Exposing the connect server would mean the need to implement rate limit controls against brute forcing, which is not mentioned at all in the current documentation. (e.g. what stops an attacker from endlessly trying out tokens?)

**Comment by verkaufer** [comment]
You're right, we don't make recommendations about rate limit. We can suggest high availability configurations, but it's ultimately up to the customer to decide the best setup for their infrastructure. We can't speak for every customer's set up, but we're happy to make suggestions and point you in the right direction.

As I mentioned earlier, setting up a load balancer or reverse proxy is one of the recommended approaches.
