### ISSUE TITLE
[Tooling] ES Lint Config does not work for Open Source

### ISSUE THREAD

**Issue by SimonBarendse** [1Password/load-secrets-action#83]
### Problem
The current ES Lint configuration does not work for the community. It depends on a closed-source 1Password project.

### Details

We're using `eslintrc.yml` from [@1password/front-end-style](https://www.npmjs.com/package/@1password/front-end-style) in this project. The public distribution of this project at NPM has been deprecated:

![image](https://github.com/user-attachments/assets/da3fbb05-4b21-433f-9001-ad6739c06363)

It looks like the [internal project](https://gitlab.1password.io/dev/foundations/web) is still receiving updates. We'll want to work with the owning team to figure out how we can use this project for open source projects, what was the original reasoning for discontinuing the NPM project, and whether we can continue that again. Alternatively, if we cannot use that project, we'll want to migrate to an open source alternative (e.g. maintaining our own ES Lint configuration in this repo).

**Comment by bxb100** [comment]
@SimonBarendse @edif2008 I found the following packages: https://www.npmjs.com/package/@1password/eslint-config and https://www.npmjs.com/package/@1password/prettier-config. Is it okay to migrate from ⁠`@1password/front-end-style` to these?
