### ISSUE TITLE
Secret is not mask

### ISSUE THREAD

**Issue by Sam-Lin-MillersLab** [1Password/load-secrets-action#9]
I still can see that from the log

```
Looking for section: devops
Looking for field: lighthouse-ci-build-token
##[debug]LIGHTHOUSE_BUILD_TOKEN='aa24f4fa-b4d2-4361-............................'
##[debug]OP_MANAGED_VARIABLES='LIGHTHOUSE_BUILD_TOKEN'
##[debug]Finished: run
##[debug]Finishing: Load secret
```

**Comment by edif2008** [comment]
Hey @Sam-Lin-MillersLab,

Thank you for raising this.
I've managed to replicate this masking issue. I've raised it with my team to further investigate this. 
I will come back to you when we update the GitHub action with a fix for this. 😊

Thank you.

**Comment by edif2008** [comment]
Hi @Sam-Lin-MillersLab ,

I've looked more into this and I've found out the following:
Masking is enabled for fields of type `Password`, as well as for item's Notes section.

Will masking work for you if you change the field's type to `Password`?

And would it be helpful if masking can be configured to be enabled for all field types?

**Comment by edif2008** [comment]
Closing the issue. Feel free to reopen if needed.

**Comment by Sam-Lin-MillersLab** [comment]
sorry, I missed your previous comment. And yes, I think that would help if there is a config for all fields
